FROM python:3

VOLUME /src
COPY pwrstat-api.py requirements.txt init.sh /src/
WORKDIR /src
RUN chmod +x /src/init.sh
RUN chmod +x /src/pwrstat-api.py
RUN pip install --trusted-host pypi.python.org -r requirements.txt
ENTRYPOINT "/src/init.sh"
